---

# FILE:            {{ role_path }}/tasks/setup/rclone/main.yml
# LICENSE:         Public Domain

- name: "abr:{{ abr_mode }} | setup | mariadb-mydumper"
# - name: "abr:{{ abr_mode }} | setup | rclone"
  block:
    - name: "abr:{{ abr_mode }} | setup | rclone | install {{ abr_packages_rclone }}"
      package:
        name: "{{ abr_packages_rclone }}"
        state: present
  rescue:
    - name: "abr:{{ abr_mode }} | setup | rclone | user message"
      fail:
        msg: >
          Default packages for rclone not found.

          For imediate suggestion, you can disable this setup step with
          'abr_setup_rclone: no' and then install manually.

          Please consider open an issue / open a pull request to the maintainer
          repository.

# SEE https://forum.rclone.org/t/rclone-as-destination-for-borgbackup/12717
# SEE https://ruderich.org/simon/notes/append-only-backups-with-restic-and-rclone