---

# FILE:            {{ role_path }}/tasks/full-temp-backup-before-restore/fs-file/main.yml
# LICENSE:         Public Domain

- name: "{{ abr__task_prefix }} | full-temp-backup-before-restore | fs-file | set_facts"
  set_fact:
    abr__ftbbr: "{{ abr_dir_paranoidmode.path }}{{ abr_uid + '__' + abr_timestamp }}"

- name: "abr:{{ abr_mode }} | full-temp-backup-before-restore | fs-file | Create {{ abr__ftbbr }}"
  file:
    path: "{{ abr__ftbbr }}"
    owner: "{{ abr_fs_owner }}"
    group: "{{ abr_fs_group }}"
    mode: "{{ abr_fs_mode }}"
    state: directory

- name: "{{ abr__task_prefix }} | full-temp-backup-before-restore | fs-file | block"
  block:
    - name: "{{ abr__task_prefix }} | full-temp-backup-before-restore | fs-file | copy {{ abr_fs_path_restore }} to {{ abr_backup_tempfolder.path }}"
      copy:
        src: "{{ abr_fs_path_restore }}" # We backup the RESTORE path (the one would be overriden)
        dest: "{{ abr__ftbbr }}"
        remote_src: yes
  rescue:
    - name: "Warn user that full-temp-backup-before-restore failed, but if is expected this step can be disabled"
      fail:
        msg: |
          full-temp-backup-before-restore failed for {{ abr_fs_path_restore }}.
          If you are doing a restore on a place that is suposed to not already
          exist, please disable full-temp-backup-before-restore with:
          'abr_paranoid: false'

- name: "{{ abr__task_prefix }} | full-temp-backup-before-restore | fs-file | ls {{ abr__ftbbr }}"
  command:
    cmd: "ls -lha {{ abr__ftbbr }}"
  register: command_ls

- name: "{{ abr__task_prefix }} | full-temp-backup-before-restore | fs-file | ls {{ abr__ftbbr }}, print"
  debug:
    msg:
      command_ls_stdout_lines: "{{ command_ls.stdout_lines | default('undefined') }}"
    # verbosity: 1

- name: "{{ abr__task_prefix }} | full-temp-backup-before-restore | fs-file | User message"
  debug:
    msg: |
      The contents from {{ abr_fs_path_restore }} have a copy at {{ abr__ftbbr }}.
      This copy will not be deleted automaticaly (needs manual clean up).
      The restore of this full-temp-backup-before-restore also does not have
      automation to be restored and, if really necessary, you should restore
      manually.