---

# FILE:            {{ role_path }}/tasks/main.yml
# LICENSE:         Public Domain

- name: "b2r | B2R {{ b2r_version }} Welcome message | Mode: {{ b2r_mode }}"
  debug:
    msg:
      # aaaa: "{{ (b2r_database is defined and b2r_database|bool) | type_debug }}"
      # bbbb: "{{ (b2r_database is defined and b2r_database|bool) | ternary('_aa', '__bb', '__ccc') }}"
      # aaaa: "{{ ((b2r_database is defined and b2r_database|bool) | ternary('__' + b2r_database, '__all-databases', '__all-databases')) }}"
      b2r:
        b2r_fs_dirs: "{{ b2r_fs_dirs }}"
        b2r_backup_disabled: "{{ b2r_backup_disabled }}"
        b2r_restore_disabled: "{{ b2r_restore_disabled }}"
      node:
        os: "{{ ansible_os_family | default('undefined') | lower }}"
        dist: "{{ ansible_distribution | default('undefined') | lower }}"
        dist_release: "{{ ansible_distribution_release | default('undefined') | lower }}"
        dist_major_ver: "{{ ansible_distribution_major_version | default('undefined') | lower }}"
        ansible_lsb: "{{ ansible_lsb | default('undefined') }}"
        # If behind NAT, this may not represent real public IPv4.
        # Alternative: https://docs.ansible.com/ansible/latest/modules/ipify_facts_module.html
        ansible_default_ipv4: "{{ ansible_default_ipv4.address | default('undefined') }}"
      run_related:
        ansible_run_tags: "{{ ansible_run_tags | default('undefined') }}"
        ansible_skip_tags: "{{ ansible_skip_tags | default('undefined') }}"
  tags:
    - b2r
    - always

## Variable loading based on node Operational System ___________________________
- name: "b2r | OS Family variables (Override with b2r_vars_osfamily)"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ (b2r_vars_osfamily is defined) | ternary(b2r_vars_osfamily, 'name-of-a-file-that-does-not-exist.yml') }}"
    - "os-family/{{ ansible_os_family | default('undefined') | lower }}.yml"
    - "os-family/{{ (ansible_os_family is defined) | ternary('untested','unknown') }}.yml"
  tags:
    - always

## Sanity Check: mydumper/myloader must have way to contact the DB server ______

- name: "~/.my.cnf stat"
  stat:
    path: "~/.my.cnf"
  when:
    - "(b2r_dbserver_password is not sameas null)"
  register: dot_my_cnf

- name: "~/.my.cnf assert"
  assert:
    that:
        - "(dot_my_cnf.stat.exists) or (b2r_dbserver_password is none)"
    success_msg: "~/.my.cnf exists. mydumper will use this file"
    fail_msg: |
        Please do at least one of these strategies:
        1. (quick) Set: b2r_dbserver_password value
        2. (recommended) create file on ~/.my.cnf where with:

        [client]
        user="{{ ansible_user_id }}"
        password="YourPasswordHere"

### DRAFT of v0.5.0 new standard, START ________________________________________
- name: "{{ b2r_mode }}.yml"
  include: "mode-{{ b2r_mode }}.yml"

### DRAFT of v0.5.0 new standard, END __________________________________________
## Run each b2r subcomponent ___________________________________________________

# - name: "setup-b2r-filesystem/main.yml"
#   include: setup-b2r-filesystem/main.yml
#   tags:
#     - setup-b2r-filesystem
#   when:
#     - b2r_setup_b2r_filesystem is sameas true

# - name: "setup-mydumper-mloader/main.yml"
#   include: setup-mydumper-mloader/main.yml
#   tags:
#     - setup-mydumper-mloader
#   when:
#     - b2r_setup_mydumper_myloader is sameas true

# - name: "setup-rclone/main.yml"
#   include: setup-rclone/main.yml
#   tags:
#     - setup-rclone
#   when:
#     - b2r_setup_rclone is sameas true

- name: "backup/main.yml"
  include: backup/main.yml
  tags:
    - backup
  when:
    - (b2r_mode == "backup")
    - (b2r_backup_disabled|bool is sameas false)

- name: "valt-send/main.yml"
  include: valt-send/main.yml
  tags:
    - valt-send
  when:
    - (b2r_mode == "backup")
    - (b2r_valt_send_disabled|bool is sameas false)

- name: "valt-receive/main.yml"
  include: valt-receive/main.yml
  tags:
    - valt-receive
  when:
    - (b2r_mode == "restore")
    - (b2r_valt_receive_disabled|bool is sameas false)

- name: "full-temp-backup-before-restore/main.yml"
  include: full-temp-backup-before-restore/main.yml
  tags:
    - full-temp-backup-before-restore
  when:
    - (b2r_mode == "restore")
    - (b2r_paranoid == true)
    - (b2r_valt_restore_disabled|bool is sameas false)

- name: "restore/main.yml"
  include: restore/main.yml
  tags:
    - restore
  when:
    - (b2r_mode == "restore")
    - (b2r_valt_restore_disabled is sameas false)
