---

# FILE:            {{ role_path }}/tasks/mode-backup.yml
# LICENSE:         Public Domain

- name: "b2r:{{ b2r_mode }} | mode-backup | TODO message"
  debug:
    msg: "Work in progress"

- name: "b2r:{{ b2r_mode }} | mode-backup | setup/main.yml"
  include: "setup/main.yml"
  when:
    - "(b2r_skip_setup|bool is sameas false)"