---

# FILE:            {{ role_path }}/tasks/mode-restore-options.yml
# LICENSE:         Public Domain
# USAGE:
#                 abr_driver: 'restore-options'


# STEP 1: RESTORE-OPTIONS ______________________ (abr_driver: 'restore-options')
#         This steps will only show what options for the current abr_bucket and
#         abr_prefix exist.
- name: "{{ abr__task_prefix }} | mode-restore-options | restore-options/main.yml"
  include: "{{ include_task_restore }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/restore-options/main.yml"
    - "{{ role_path }}/tasks/restore-options/main.yml"
  when:
    - "(abr_skip_maintask|bool is sameas false)"
  loop_control:
    loop_var: "include_task_restore"
  # when:
  #   - "(abr_skip_setup|bool is sameas false)"
