---

# FILE:            {{ role_path }}/tasks/mode-restore-options.yml
# LICENSE:         Public Domain

- name: "abr:{{ abr_mode }} | mode-restore-options | TODO message"
  debug:
    msg: "Work in progress"

- name: "abr:{{ abr_mode }} | mode-restore-options | setup/main.yml"
  include: "setup/main.yml"
  when:
    - "(abr_skip_setup|bool is sameas false)"
