---

# FILE:            {{ role_path }}/tasks/mode-restore.yml
# LICENSE:         Public Domain

- name: "{{ abr__task_prefix }} | mode-restore | setup/main.yml"
  include: "{{ include_task_mode_restore_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/setup/main.yml"
    - "{{ role_path }}/tasks/setup/main.yml"
  loop_control:
    loop_var: "include_task_mode_restore_item"
  when:
    - "(abr_skip_setup|bool is sameas false)"

- name: "{{ abr__task_prefix }} | mode-restore | download/main.yml"
  include: "{{ include_task_mode_restore_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/download/main.yml"
    - "{{ role_path }}/tasks/download/main.yml"
  loop_control:
    loop_var: "include_task_mode_restore_item"

- name: "{{ abr__task_prefix }} | mode-restore | decompress/main.yml"
  include: "{{ include_task_mode_restore_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/decompress/main.yml"
    - "{{ role_path }}/tasks/decompress/main.yml"
  when:
    - "(abr_strategy_compression is defined) and (abr_strategy_compression)"
  loop_control:
    loop_var: "include_task_mode_restore_item"

- name: "{{ abr__task_prefix }} | mode-restore | full-temp-backup-before-restore/main.yml"
  include: "{{ include_task_mode_restore_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/full-temp-backup-before-restore/main.yml"
    - "{{ role_path }}/tasks/full-temp-backup-before-restore/main.yml"
  loop_control:
    loop_var: "include_task_mode_restore_item"

- name: "{{ abr__task_prefix }} | mode-restore | restore/main.yml"
  include: "{{ include_task_mode_restore_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/restore/main.yml"
    - "{{ role_path }}/tasks/restore/main.yml"
  loop_control:
    loop_var: "include_task_mode_restore_item"