---

# FILE:            {{ role_path }}/tasks/mode-restore.yml
# LICENSE:         Public Domain

- name: "abr:{{ abr_mode }} | mode-restore | TODO message"
  debug:
    msg: "Work in progress"

- name: "abr:{{ abr_mode }} | mode-restore-options | setup/main.yml"
  include: "setup/main.yml"
  when:
    - "(abr_skip_setup|bool is sameas false)"

- name: "valt-receive/main.yml"
  include: valt-receive/main.yml
#   tags:
#     - valt-receive
#   when:
#     - (abr_mode == "restore")
#     - (abr_valt_receive_disabled|bool is sameas false)

- name: "full-temp-backup-before-restore/main.yml"
  include: full-temp-backup-before-restore/main.yml
#   tags:
#     - full-temp-backup-before-restore
  when:
    - (abr_paranoid == true)
#     - (abr_mode == "restore")
#     - (abr_valt_restore_disabled|bool is sameas false)

- name: "restore/main.yml"
  include: restore/main.yml
#   tags:
#     - restore
#   when:
#     - (abr_mode == "restore")
#     - (abr_valt_restore_disabled is sameas false)