---

# FILE:            {{ role_path }}/tasks/setup/mariadb-mydumper/main.yml
# LICENSE:         Public Domain
# SEE:             https://docs.ansible.com/ansible/latest/modules/package_module.html

- name: "{{ abr__task_prefix }} | setup | mariadb-mydumper"
# - name: "abr | setup-mydumper-mloader"
  block:
    - name: "{{ abr__task_prefix }} | setup | mariadb-mydumper | install {{ abr_packages_mydumpermyloader }}"
      package:
        name: "{{ abr_packages_mydumpermyloader }}"
        state: present
  rescue:
    - name: "{{ abr__task_prefix }} | setup | mariadb-mydumper | user message"
      fail:
        msg: >
          Default packages for mydumper/myloader not found.

          For imediate suggestion, you can disable this setup step with
          'abr_setup_mydumper_myloader: no' and then install manually.

          Please consider open an issue / open a pull request to the maintainer
          repository.