---

# FILE:            {{ role_path }}/tasks/setup/main.yml
# LICENSE:         Public Domain

# - name: "abr:{{ abr_mode }} | setup | TODO message"
#   debug:
#     msg: "Work in progress"

- name: "abr:{{ abr_mode }} | upload"
  include: "{{ rclone_item }}"
  with_first_found:
    - "{{ role_path }}/tasks/upload/{{ abr_driver_rclone | default('dont-exist') }}/main.yml"
    - "{{ role_path }}/tasks/upload/unknown.yml"
  loop_control:
    loop_var: "rclone_item"
  vars:
    upload_unknown_message: "Critical error! Driver for upload not found!"
