---

# FILE:            {{ role_path }}/tasks/upload/main.yml
# LICENSE:         Public Domain

- name: "abr:{{ abr_mode }} | upload"
  include: "{{ rclone_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/upload/{{ abr_driver_rclone | default('dont-exist') }}/main.yml"
    - "{{ role_path }}/tasks/upload/{{ abr_driver_rclone | default('dont-exist') }}/main.yml"
    - "{{ abr_overrides_directory }}/tasks/common/unknown.yml"
    - "{{ role_path }}/tasks/common/unknown.yml"
  loop_control:
    loop_var: "rclone_item"
  vars:
    # unknown_message: "Critical error! Driver for upload not found!"
    unknown_message: "Critical error! Upload driver driver '{{ abr_driver_rclone }}' not found on {{ role_path }} and {{ abr_overrides_directory }}"
