---

# Backup playbooks _____________________________________________________________
- name: "Converge: backup fs-directory"
  hosts: all
  remote_user: root
  vars:

    # backup? restore? restore-options?
    abr_mode: backup

    abr_driver: "fs-directory"
    abr_strategy_compression: "targz-default"
    abr_strategy_encryption: "base64-default"
    abr_fs_path: "/var/www/site-1/"
    abr_prefix: "www-site-1/"
    abr_timestamped: false

    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ansible-adhoc-backup-restore

- name: "Converge: backup fs-file"
  hosts: all
  remote_user: root
  vars:

    # backup? restore? restore-options?
    abr_mode: backup

    abr_uid: "single-file.csv"
    abr_driver: "fs-file"
    abr_strategy_compression: "targz-default"
    abr_strategy_encryption: "base64-default"
    abr_fs_path: "/var/www/single-file.csv"
    abr_prefix: "csv-backups/"
    abr_timestamped: false

    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ansible-adhoc-backup-restore

# Force need of restore playbooks ______________________________________________
- name: "Converge: simulate data corruption"
  hosts: all
  remote_user: root
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: "/var/www/single-file.csv: error error error"
      copy:
        content: "error error error!"
        dest: "/var/www/single-file.csv"

    - name: "/var/www/site-1/index.html: error error error"
      copy:
        content: "error error error!"
        dest: "/var/www/site-1/index.html"

    - name: "/var/www/site-1/style.css: /* error error error */"
      copy:
        content: "/* error error error */"
        dest: "/var/www/site-1/style.css"

    - name: "/var/www/site-1/script.js: /* error error error */"
      copy:
        content: "/* error error error */"
        dest: "/var/www/site-1/script.js"

# Restore playbooks ____________________________________________________________
- name: "Converge: restore fs-directory"
  hosts: all
  remote_user: root
  vars:

    # backup? restore? restore-options?
    abr_mode: restore


    abr_driver: "fs-directory"
    abr_strategy_compression: "targz-default"
    abr_strategy_encryption: "base64-default"
    abr_fs_path: "/var/www/site-1/"
    abr_prefix: "www-site-1/"
    abr_timestamped: false

    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ansible-adhoc-backup-restore

- name: "Converge: restore fs-file"
  hosts: all
  remote_user: root
  vars:

    # backup? restore? restore-options?
    abr_mode: restore

    abr_uid: "single-file.csv"
    abr_driver: "fs-file"
    abr_strategy_compression: "targz-default"
    abr_strategy_encryption: "base64-default"
    abr_fs_path: "/var/www/single-file.csv"
    abr_prefix: "csv-backups/"
    abr_timestamped: false

    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ansible-adhoc-backup-restore

  # pre_tasks:
  #   - name: "Set ISCONTEINER=1"
  #     shell: "export ISCONTEINER=1" # noqa 305
  #     # command: "export ISCONTEINER=1"
  #     changed_when: false # This specific pre_task break Idempotence if not ignored