---

- name: "Converge: backup"
  hosts: all
  remote_user: root
  vars:
    abr_mode: backup
    abr_driver: "fs-folder"
    abr_fs_path: "/var/www/site-1/"
    abr_prefix: "www-site-1/"
    abr_timestamped: false

    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ansible-adhoc-backup-restore

- name: "Converge: simulate data corruption"
  hosts: all
  remote_user: root
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: "/var/www/site-1/index.html: error error error"
      copy:
        content: "error error error!"
        dest: "/var/www/site-1/index.html"

    - name: "/var/www/site-1/style.css: /* error error error */"
      copy:
        content: "/* error error error */"
        dest: "/var/www/site-1/style.css"

    - name: "/var/www/site-1/script.js: /* error error error */"
      copy:
        content: "/* error error error */"
        dest: "/var/www/site-1/script.js"

- name: "Converge: restore"
  hosts: all
  remote_user: root
  vars:
    abr_mode: restore
    abr_driver: "fs-folder"
    abr_fs_path: "/var/www/site-1/"
    abr_prefix: "www-site-1/"
    abr_timestamped: false

    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: ansible-adhoc-backup-restore

  # pre_tasks:
  #   - name: "Set ISCONTEINER=1"
  #     shell: "export ISCONTEINER=1" # noqa 305
  #     # command: "export ISCONTEINER=1"
  #     changed_when: false # This specific pre_task break Idempotence if not ignored