---

# FILE:            {{ role_path }}/tasks/compress/main.yml
# LICENSE:         Public Domain
# SEE:             https://wiki.archlinux.org/index.php/Archiving_and_compression
# SEE:             https://github.com/tahoe-lafs/zfec
# Tip from zfec:
#    "It is important to do things in order: first archive, then compress, then
#     either encrypt or integrity-check, then erasure code."

- name: "{{ abr__task_prefix }} | compress | include {{ abr_strategy_compression | default('dont-exist') }}"
  include: "{{ include_task_compress_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/compress/{{ abr_strategy_compression | default('dont-exist') }}/main.yml"
    - "{{ role_path }}/tasks/compress/{{ abr_strategy_compression | default('dont-exist') }}/main.yml"
    - "{{ abr_overrides_directory }}/tasks/common/unknown.yml"
    - "{{ role_path }}/tasks/common/unknown.yml"
  loop_control:
    loop_var: "include_task_compress_item"
  vars:
    unknown_message: "Critical error! compression strategy '{{ abr_strategy_compression }}' not found on {{ role_path }} or {{ abr_overrides_directory }}"
