---

# FILE:            {{ role_path }}/tasks/restore/main.yml
# LICENSE:         Public Domain

- name: "{{ abr__task_prefix }} | restore {{ abr__task_suffix }}"
  include: "{{ include_task_restore_item }}"
  with_first_found:
    - "{{ abr_overrides_directory }}/tasks/restore/{{ abr_driver | default('dont-exist') }}/main.yml"
    - "{{ role_path }}/tasks/restore/{{ abr_driver | default('dont-exist') }}/main.yml"
    - "{{ abr_overrides_directory }}/tasks/common/unknown.yml"
    - "{{ role_path }}/tasks/common/unknown.yml"
  loop_control:
    loop_var: "include_task_restore_item"
  vars:
    unknown_message: "Critical error! restore driver '{{ abr_driver }}' not found on {{ role_path }} or {{ abr_overrides_directory }}"