---

# FILE:            {{ role_path }}/tasks/backup/main.yml
# LICENSE:         Public Domain

- name: "MRM | backup | TODO message"
  debug:
    msg: "Work in progress"

- name: "Run prepared mydumper_command"
  shell: >
    mydumper
    --outputdir='{{ this_mydumper_outputdir }}'
    {{ mydumper_command_append | default('') }}
#   command:
#     argv:
#       - "mydumper"
#       - "--outputdir='{{ this_mydumper_outputdir }}'"
#       # - ""
  when:
    - (mydumper_command is undefined)
  register: command_result
