---

# FILE:            {{ role_path }}/tasks/backup/mydumper.yml
# LICENSE:         Public Domain

- name: "b2r | backup | debug (requires -v, -vv, -vvv, or -vvvv)"
  debug:
    msg:
      b2r_mydumper_outputdir: "{{ b2r_mydumper_outputdir | default('undefined') }}"
      # result: "{{ (b2r_database is defined and b2r_database and b2r_database|length > 0) }}"
      # result2: "{{ (b2r_database is defined and b2r_database and b2r_database|length > 0) | ternary('_aaaaa_', '_bbbb_', '_isnull_')}}"
      # result: "{{ ((b2r_database is defined and b2r_database and b2r_database|length > 0) | ternary('_' + b2r_database + '_', '_all-databases_')) }}"
    verbosity: 1

- name: "Run prepared mydumper_command"
  shell: >
    mydumper
    --outputdir='{{ b2r_mydumper_outputdir }}'
    {{ b2r_mydumper_append | default('') }}
  register: mydumper_command_result

- name: "Compress {{ b2r_mydumper_outputdir }} into /var/local/b2r/temp/output.xz"
  archive:
    path: "{{ b2r_mydumper_outputdir }}"
    #dest: "{{ b2r_mydumper_outputdir }}.xz"
    dest: "/var/local/b2r/temp/output.xz"
    # format: "xz"
    force_archive: yes
    remove: yes
  register: archive_command_result

- name: "Inform new path of file (before was a folder)"
  set_fact:
    # b2r_backup_rclone_source: "{{ b2r_mydumper_outputdir }}.xz"
    b2r_backup_rclone_source: "/var/local/b2r/temp/output.xz"

- name: "b2r | backup | debug (requires -v, -vv, -vvv, or -vvvv)"
  debug:
    msg:
      mydumper_command_result: "{{ mydumper_command_result | default('undefined') }}"
      archive_command_result: "{{ archive_command_result | default('undefined') }}"
    # verbosity: 1