---

# FILE:            {{ role_path }}/tasks/upload/rclone/main.yml
# LICENSE:         Public Domain
# SEE:             https://forum.rclone.org/t/can-rclone-be-run-solely-with-command-line-options-no-config-no-env-vars/6314/2
# SEE:             https://github.com/rclone/rclone/issues/2449 (Title: Allow creation of backends from command line parameters)

- name: "{{ abr__task_prefix }} | upload | rclone-default | debug (requires -v)"
# - name: "abr | valt-send | debug (requires -v, -vv, -vvv, or -vvvv)"
  debug:
    msg:
      abr_backup_rclone_command: "{{ abr_backup_rclone_command | default('undefined') }}"
      abr_rclone_enviroment: "{{ abr_rclone_enviroment | default('undefined') }}"
      abr__extensions_arr: "{{ abr__extensions_arr | default('undefined') }}"
      abr__extension: "{{ abr__extension | default('undefined') }}"
      abr__extension2: "{{ abr__extension2 | default('undefined') }}"
      abr__extension_aaa: "{{ abr__extensions_arr | join('.') }}"
      abr__filename_extension: "{{ abr__filename_extension }}"
      abr__filename_timestamped: "{{ abr__filename_timestamped | default('undefined') }}"
      abr__filename_timestamped_withextensions: "{{ abr__filename_timestamped_withextensions | default('undefined') }}"
    verbosity: 1

- name: "{{ abr__task_prefix }} | upload | rclone-default | rclone command"
  command:
    cmd: "{{ abr_backup_rclone_command }}"
  environment: "{{ abr_rclone_enviroment }}"
  register: command_result
